import { BarChart, Donut, Sparkline } from "@/components/charts";
import { Icon } from "@/components/icons";
import { demoAlerts, demoMetrics, demoThreats, demoVisitors, threatSeries, trafficSeries } from "@/lib/demo";

function Status({ children, tone = "safe" }: { children: React.ReactNode; tone?: string }) { return <span className={`statusTag ${tone}`}>{children}</span>; }

export function ClientDashboard() {
  return <div className="pageWrap">
    <div className="pageHeader"><div><div className="breadcrumbs">WebShield <span>/</span> Overview</div><h1>Security Overview</h1><p>Monitor visitor activity, threat signals and security posture across your websites.</p></div><div className="headerActions"><span className="demoBadge large">DEMO MODE</span><button className="ghostBtn small">Last 24 hours⌄</button></div></div>
    <div className="metricGrid">{demoMetrics.map(([label,value,delta],i)=><article className="metricCard" key={label}><div className="metricTop"><span>{label}</span><div className={`metricIcon i${i}`}><Icon name={i===0||i===1?"visitors":i===5?"globe":i===4?"shield":"threat"}/></div></div><strong>{value}</strong><small className={delta.includes("+")?"up":"muted"}>{delta}</small>{i<2&&<Sparkline values={i===0?trafficSeries.slice(-8):[2,5,3,8,6,9,11,10]} label={`${label} trend`}/>}</article>)}</div>
    <div className="dashboardGrid twoThirds">
      <article className="panel"><div className="panelHead"><div><h3>Visitor Activity</h3><p>Requests observed across demo website traffic</p></div><div className="legend"><span className="cyanDot"/> Visitors <span className="redDot"/> Threat signals</div></div><div className="lineChart"><div className="axisLabels"><span>150</span><span>100</span><span>50</span><span>0</span></div><Sparkline values={trafficSeries} label="Visitor activity"/><div className="threatLine"><Sparkline values={threatSeries} label="Threat activity"/></div><div className="timeAxis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>Now</span></div></div></article>
      <article className="panel"><div className="panelHead"><div><h3>Threat Score</h3><p>Weighted demo risk signal</p></div><Status>LOW RISK</Status></div><div className="scoreBody"><Donut value={28} label="Risk score"/><div className="scoreLegend"><span><i className="low"/>Low <b>72%</b></span><span><i className="medium"/>Medium <b>18%</b></span><span><i className="high"/>High <b>8%</b></span><span><i className="critical"/>Critical <b>2%</b></span></div></div></article>
    </div>
    <div className="dashboardGrid equal">
      <article className="panel"><div className="panelHead"><div><h3>Threat Categories</h3><p>Detected demo event distribution</p></div><button className="textButton">View center →</button></div><BarChart data={[["Bot traffic",38],["Brute force",26],["Suspicious IP",18],["Injection",12],["Other",6]]}/></article>
      <article className="panel"><div className="panelHead"><div><h3>Geographic Traffic</h3><p>Top visitor countries</p></div></div><BarChart data={[["India",44],["United States",23],["Germany",14],["Singapore",11],["Other",8]]}/></article>
    </div>
    <article className="panel tablePanel"><div className="panelHead"><div><h3>Recent Security Events</h3><p>Latest normalized security events from the demo provider</p></div><a href="/app/threat-center" className="textButton">View all →</a></div><div className="tableScroll"><table><thead><tr><th>Event</th><th>Severity</th><th>Source IP</th><th>Target</th><th>Risk</th><th>Action</th><th>Time</th></tr></thead><tbody>{demoThreats.map(t=><tr key={t.id}><td><b>{t.type}</b><small>{t.id}</small></td><td><Status tone={t.severity.toLowerCase()}>{t.severity}</Status></td><td className="mono">{t.sourceIp}</td><td className="mono">{t.targetUrl}</td><td><span className="riskScore">{t.riskScore}</span></td><td>{t.action}</td><td>{t.timestamp}</td></tr>)}</tbody></table></div></article>
    <div className="dashboardGrid equal">
      <article className="panel"><div className="panelHead"><div><h3>Suspicious Visitors</h3><p>Highest-risk visitor sessions</p></div></div>{demoVisitors.filter(v=>v.riskScore>60).map(v=><div className="eventRow" key={v.id}><span className={`riskOrb r${v.riskScore}`}>{v.riskScore}</span><div><b>{v.ip}</b><small>{v.country} · {v.device} · {v.url}</small></div><Status tone={v.status.toLowerCase()}>{v.status}</Status></div>)}</article>
      <article className="panel"><div className="panelHead"><div><h3>Recent Alerts</h3><p>Priority security notifications</p></div></div>{demoAlerts.map(([title,body,time,severity])=><div className="eventRow" key={title}><span className={`alertIcon ${severity.toLowerCase()}`}><Icon name="bell"/></span><div><b>{title}</b><small>{body}</small></div><span className="eventTime">{time}</span></div>)}</article>
    </div>
  </div>;
}

export function AdminDashboard() {
  const stats = [["Total Clients","142","+9 this month"],["Active Websites","318","296 protected"],["Total Visitors","8.4M","30d demo aggregate"],["Threat Events","81.2K","30d demo aggregate"],["Blocked Requests","214K","30d demo aggregate"],["System Health","99.99%","Demo status"]];
  return <div className="pageWrap"><div className="pageHeader"><div><div className="breadcrumbs">WebShield <span>/</span> Administration</div><h1>Platform Control Center</h1><p>Administrative oversight for clients, websites, subscriptions and security event operations.</p></div><span className="demoBadge large">DEMO MODE</span></div><div className="metricGrid">{stats.map(([a,b,c],i)=><article className="metricCard" key={a}><div className="metricTop"><span>{a}</span><div className="metricIcon"><Icon name={i<2?"visitors":i===5?"shield":"chart"}/></div></div><strong>{b}</strong><small className="muted">{c}</small></article>)}</div><div className="dashboardGrid twoThirds"><article className="panel"><div className="panelHead"><div><h3>Platform activity</h3><p>Demo aggregate events across tenants</p></div></div><div className="lineChart adminChart"><Sparkline values={[44,55,49,68,72,81,77,94,88,112,105,128,122,137]} label="Platform activity"/></div></article><article className="panel"><div className="panelHead"><div><h3>Subscription mix</h3><p>Demo tenant distribution</p></div></div><BarChart data={[["Free",42],["Starter",31],["Business",21],["Enterprise",6]]}/></article></div><article className="panel"><div className="panelHead"><div><h3>Operations queue</h3><p>Items requiring platform review</p></div></div>{[["4 critical threat events need review","Security events","CRITICAL"],["7 website verification failures","Websites","HIGH"],["3 billing actions pending","Subscriptions","MEDIUM"],["12 open support tickets","Support","LOW"]].map(([x,y,z])=><div className="eventRow" key={x}><span className={`alertIcon ${z.toLowerCase()}`}><Icon name="bell"/></span><div><b>{x}</b><small>{y}</small></div><Status tone={z.toLowerCase()}>{z}</Status></div>)}</article></div>;
}
