import Link from "next/link";
import { Icon } from "@/components/icons";
import { BarChart, Donut } from "@/components/charts";
import { demoAlerts, demoThreats, demoVisitors, demoWebsites } from "@/lib/demo";

function Header({title,text,action}:{title:string;text:string;action?:string}){
  return <div className="pageHeader"><div><div className="breadcrumbs">WebShield <span>/</span> {title}</div><h1>{title}</h1><p>{text}</p></div><div className="headerActions"><span className="demoBadge large">DEMO MODE</span>{action&&<button className="btn small"><Icon name="plus"/>{action}</button>}</div></div>;
}
function Tag({children,tone="safe"}:{children:React.ReactNode;tone?:string}){return <span className={`statusTag ${tone}`}>{children}</span>}
function Panel({title,text,children}:{title:string;text?:string;children:React.ReactNode}){return <article className="panel"><div className="panelHead"><div><h3>{title}</h3>{text&&<p>{text}</p>}</div></div>{children}</article>}

function Visitors({history=false}:{history?:boolean}){
  return <div className="pageWrap"><Header title={history?"Visitor History":"Live Visitors"} text={history?"Search and investigate previous visitor sessions.":"Real-time style activity feed from the separated demo telemetry provider."}/><div className="toolbar"><div className="searchBox"><Icon name="search"/><input placeholder="Search IP, visitor ID, URL…"/></div>{["Country","Risk","Device","Status"].map(x=><button className="filterBtn" key={x}>{x}⌄</button>)}</div><article className="panel tablePanel"><div className="tableScroll"><table><thead><tr><th>Visitor</th><th>IP</th><th>Location</th><th>Device</th><th>Browser / OS</th><th>Request</th><th>Risk</th><th>Status</th><th>Time</th></tr></thead><tbody>{demoVisitors.map(v=><tr key={v.id}><td><b>{v.id}</b></td><td className="mono">{v.ip}</td><td>{v.city}<small>{v.country}</small></td><td>{v.device}</td><td>{v.browser}<small>{v.os}</small></td><td className="mono"><b>{v.method}</b> {v.url}</td><td><span className="riskScore">{v.riskScore}</span></td><td><Tag tone={v.status.toLowerCase()}>{v.status}</Tag></td><td>{v.timestamp}</td></tr>)}</tbody></table></div></article></div>
}
function ThreatCenter(){return <div className="pageWrap"><Header title="Threat Center" text="Investigate normalized threat events, severity, source, target and risk score."/><div className="metricGrid compact">{[["Open threats","18"],["Critical","4"],["High severity","23"],["Blocked today","1,284"]].map(([a,b])=><article className="metricCard" key={a}><span>{a}</span><strong>{b}</strong><small>Demo telemetry</small></article>)}</div><article className="panel tablePanel"><div className="tableScroll"><table><thead><tr><th>ID</th><th>Type</th><th>Severity</th><th>Source IP</th><th>Target</th><th>Risk</th><th>Status</th><th>Action</th></tr></thead><tbody>{demoThreats.map(t=><tr key={t.id}><td><b>{t.id}</b><small>{t.timestamp}</small></td><td>{t.type}</td><td><Tag tone={t.severity.toLowerCase()}>{t.severity}</Tag></td><td className="mono">{t.sourceIp}</td><td className="mono">{t.targetUrl}</td><td><span className="riskScore">{t.riskScore}</span></td><td>{t.status}</td><td><Tag tone="blocked">{t.action}</Tag></td></tr>)}</tbody></table></div></article></div>}
function Firewall(){return <div className="pageWrap"><Header title="Firewall" text="Configure provider-neutral firewall policy. V1 does not claim live enforcement." action="Create Rule"/><div className="dashboardGrid twoThirds"><Panel title="Rule builder" text="Configuration preview"><div className="ruleBuilder"><b>IF</b><span>Country = selected</span><b>AND</b><span>Risk Score &gt; 80</span><b>THEN</b><Tag tone="blocked">BLOCK</Tag></div><div className="buttonRow"><button className="btn small">Save demo rule</button><button className="ghostBtn small">Test rule</button></div></Panel><Panel title="Available actions" text="Decision-engine contract">{[["ALLOW","Pass request"],["BLOCK","Reject request"],["CHALLENGE","Request verification"],["RATE_LIMIT","Throttle request"]].map(([a,b])=><div className="decisionRow" key={a}><Tag tone={a.toLowerCase()}>{a}</Tag><span>{b}</span></div>)}</Panel></div><Panel title="Firewall rules" text="Demo configuration only"><div className="tableScroll"><table><thead><tr><th>Name</th><th>Condition</th><th>Action</th><th>Status</th></tr></thead><tbody>{[["Block high-risk","Risk > 90","BLOCK","Active"],["Challenge automation","Bot + Risk > 60","CHALLENGE","Active"],["Login rate limit","/login > 20/min","RATE_LIMIT","Active"]].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td><Tag tone={r[2].toLowerCase()}>{r[2]}</Tag></td><td><Tag>{r[3]}</Tag></td></tr>)}</tbody></table></div></Panel></div>}
function Websites(){return <div className="pageWrap"><Header title="Websites" text="Connect, verify and manage multiple websites." action="Add Website"/><div className="websiteGrid">{demoWebsites.map(w=><article className="websiteCard" key={w.domain}><div className="siteIcon"><Icon name="globe"/></div><div><h3>{w.domain}</h3><p>SSL: {w.ssl} · Risk: {w.risk}</p><Tag tone={w.status==="PROTECTED"?"safe":"medium"}>{w.status}</Tag><p>Integration: <b>{w.integration}</b></p><button className="ghostBtn small">Manage</button></div></article>)}</div><Panel title="Integration setup" text="A site is never labelled protected before verification and a real provider connection."><div className="steps">{[["1","Enter domain"],["2","Generate token"],["3","Verify domain"],["4","Install integration"],["5","Activate protection"]].map(([n,a])=><div className="step" key={n}><span>{n}</span><b>{a}</b></div>)}</div></Panel></div>}
function Analytics(){return <div className="pageWrap"><Header title="Analytics" text="Visitor and security analytics with date-range controls."/><div className="rangeTabs">{["Today","Yesterday","7 Days","30 Days","90 Days","Custom"].map((x,i)=><button className={i===2?"active":""} key={x}>{x}</button>)}</div><div className="dashboardGrid equal"><Panel title="Traffic sources"><BarChart data={[["Organic",42],["Direct",31],["Referral",17],["Social",8]]}/></Panel><Panel title="Severity distribution"><div className="donutRow"><Donut value={72} label="Safe traffic"/><div className="scoreLegend"><span>Low <b>72%</b></span><span>Medium <b>18%</b></span><span>High <b>8%</b></span><span>Critical <b>2%</b></span></div></div></Panel></div></div>}
function Reports(){return <div className="pageWrap"><Header title="Reports" text="Generate daily, weekly, monthly, visitor, threat and firewall reports."/><div className="reportGrid">{["Daily Security Report","Weekly Security Report","Monthly Security Report","Visitor Report","Threat Report","Firewall Report"].map(x=><article className="reportCard" key={x}><Icon name="chart"/><div><h3>{x}</h3><p>Demo dataset · PDF integration ready · CSV export architecture</p></div><div className="rowButtons"><button className="ghostBtn small">View</button><button className="ghostBtn small">Export CSV</button></div></article>)}</div></div>}
function Alerts(){return <div className="pageWrap"><Header title="Alerts" text="Security notification center and channel preferences."/><div className="dashboardGrid equal"><Panel title="Recent alerts">{demoAlerts.map(([a,b,c,d])=><div className="eventRow" key={a}><span className={`alertIcon ${d.toLowerCase()}`}><Icon name="bell"/></span><div><b>{a}</b><small>{b}</small></div><span>{c}</span></div>)}</Panel><Panel title="Notification channels" text="Dashboard is active; email/webhook remain integration-ready.">{[["Dashboard","Enabled"],["Email","Integration ready"],["Webhook","Integration ready"]].map(([a,b])=><div className="decisionRow" key={a}><b>{a}</b><Tag tone={b==="Enabled"?"safe":"medium"}>{b}</Tag></div>)}</Panel></div></div>}
function ApiIntegrations(){return <div className="pageWrap"><Header title="API & Integrations" text="Scoped API key and signed webhook architecture. Full secrets are never shown after creation." action="Create Key"/><div className="dashboardGrid equal"><Panel title="API Keys"><div className="apiKeyRow"><Icon name="key"/><div><b>Production collector</b><code>wsk_live_••••••••9f2a</code><small>Demo prefix only</small></div><button className="dangerButton">Revoke</button></div></Panel><Panel title="Webhooks"><div className="emptyMini"><Icon name="globe"/><b>No production webhooks configured</b><p>Set WEBHOOK_SECRET server-side before connecting endpoints.</p></div></Panel></div><Panel title="REST boundaries"><div className="endpointGrid">{["dashboard","websites","visitors","threats","firewall","analytics","reports","alerts","api-keys","webhooks","billing","support"].map(x=><code key={x}>GET /api/{x}</code>)}</div></Panel></div>}
function Billing(){return <div className="pageWrap"><Header title="Billing" text="Subscription foundation. No fake payment processing is performed."/><div className="pricingGrid appPricing">{[["FREE","₹0","1 website"],["STARTER","Coming soon","3 websites"],["BUSINESS","Coming soon","10 websites"],["ENTERPRISE","Contact us","Custom"]].map(([a,b,c],i)=><article className={`priceCard ${i===0?"current":""}`} key={a}><h3>{a}</h3><strong>{b}</strong><p>{c}</p><button className="ghostBtn small">{i===0?"Current plan":"Integration ready"}</button></article>)}</div></div>}
function Team(){return <div className="pageWrap"><Header title="Team" text="Organization members and role-based access." action="Invite Member"/><Panel title="RBAC roles" text="OWNER, ADMIN, SECURITY_ANALYST, MEMBER and VIEWER are enforced server-side when production auth is configured."><div className="endpointGrid">{["OWNER","ADMIN","SECURITY_ANALYST","MEMBER","VIEWER"].map(x=><code key={x}>{x}</code>)}</div></Panel></div>}
function Settings({support=false}:{support?:boolean}){return <div className="pageWrap"><Header title={support?"Support":"Settings"} text={support?"Track operational support requests.":"Organization, security, notification and retention preferences."} action={support?"New Ticket":undefined}/>{support?<Panel title="Support tickets">{[["#WS-1042","Website verification","OPEN"],["#WS-1038","Webhook setup","PENDING"],["#WS-1021","Analytics export","RESOLVED"]].map(([a,b,c])=><div className="eventRow" key={a}><b>{a}</b><span>{b}</span><Tag tone={c==="RESOLVED"?"safe":"medium"}>{c}</Tag></div>)}</Panel>:<Panel title="Security defaults"><div className="settingsGrid">{["Require verified websites","Audit sensitive actions","Mask secret keys","Always label demo telemetry"].map(x=><div className="toggleRow" key={x}><b>{x}</b><i className="toggle on"/></div>)}</div></Panel>}</div>}
function AdminGeneric({slug}:{slug:string}){const title=slug.split("-").map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(" ");return <div className="pageWrap"><Header title={title} text={`Administrative ${title.toLowerCase()} management. Demo data only.`}/><Panel title={`${title} records`}><div className="tableScroll"><table><thead><tr><th>Record</th><th>Context</th><th>Status</th><th>State</th></tr></thead><tbody>{[["WS-001","Savrdh Technologies","ACTIVE","Healthy"],["WS-002","Demo workspace","PENDING","Review"],["WS-003","Security operation","DEMO","Observed"]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={c}>{i===0?<b>{c}</b>:i===2?<Tag>{c}</Tag>:c}</td>)}</tr>)}</tbody></table></div></Panel></div>}

export function ClientModule({slug}:{slug:string}){
  if(slug==="live-visitors")return <Visitors/>;
  if(slug==="visitor-history")return <Visitors history/>;
  if(slug==="threat-center")return <ThreatCenter/>;
  if(slug==="firewall")return <Firewall/>;
  if(slug==="websites")return <Websites/>;
  if(slug==="analytics")return <Analytics/>;
  if(slug==="reports")return <Reports/>;
  if(slug==="alerts")return <Alerts/>;
  if(slug==="api-integrations")return <ApiIntegrations/>;
  if(slug==="billing")return <Billing/>;
  if(slug==="team")return <Team/>;
  if(slug==="settings")return <Settings/>;
  if(slug==="support")return <Settings support/>;
  return <div className="pageWrap"><Header title="Module" text="Unknown WebShield route."/><Link className="btn" href="/app/dashboard">Return to dashboard</Link></div>;
}
export function AdminModule({slug}:{slug:string}){return slug==="system-settings"?<Settings/>:<AdminGeneric slug={slug}/>}
