export type FeatureStatus = "LIVE PASSIVE" | "DEMO TELEMETRY" | "INTEGRATION READY";

export type FeatureDefinition = {
  title: string;
  group: string;
  description: string;
  status: FeatureStatus;
  capabilities: string[];
};

export const featureCatalog: Record<string, FeatureDefinition> = {
  "real-time-monitoring": { title:"Real-Time Monitoring", group:"Core Security Engine", description:"Unified monitoring layer for visitor, request and environment signals.", status:"DEMO TELEMETRY", capabilities:["Visitor Tracking","IP Monitoring","Country / Location","Device","Browser","Operating System"] },
  "visitor-tracking": { title:"Visitor Tracking", group:"Core Security Engine", description:"Observe visitor sessions and request activity across connected websites.", status:"DEMO TELEMETRY", capabilities:["Visitor ID","First seen / last seen","Current page","Session status","Risk score","Request count"] },
  "ip-monitoring": { title:"IP Monitoring", group:"Core Security Engine", description:"Monitor source IPs and correlate them with session and threat signals.", status:"DEMO TELEMETRY", capabilities:["Source IP","Request frequency","Risk score","Associated sessions","Threat history","Allow / block state"] },
  "country-location": { title:"Country / Location", group:"Core Security Engine", description:"Geographic context for observed website traffic.", status:"DEMO TELEMETRY", capabilities:["Country","Region","City","Traffic volume","Threat volume","Country policy state"] },
  "device-monitoring": { title:"Device", group:"Core Security Engine", description:"Device classification for observed visitor sessions.", status:"DEMO TELEMETRY", capabilities:["Desktop","Mobile","Tablet","Server / automation","Unknown device","Risk correlation"] },
  "browser-monitoring": { title:"Browser", group:"Core Security Engine", description:"Browser intelligence for visitor and request telemetry.", status:"DEMO TELEMETRY", capabilities:["Browser family","Browser version","Headless indicator","User-agent summary","Session count","Risk correlation"] },
  "os-monitoring": { title:"Operating System", group:"Core Security Engine", description:"Operating-system context for observed visitor sessions.", status:"DEMO TELEMETRY", capabilities:["OS family","OS version","Device mapping","Session count","Threat correlation"] },

  "threat-detection": { title:"Threat Detection", group:"Core Security Engine", description:"Normalize suspicious request signals into understandable security events.", status:"INTEGRATION READY", capabilities:["Suspicious IP","Bot Detection","Malicious Requests","Brute Force","XSS Attempts","SQL Injection Attempts","DDoS Indicators"] },
  "suspicious-ip": { title:"Suspicious IP", group:"Threat Detection", description:"Flag IP addresses based on connected reputation and behavioral signals.", status:"INTEGRATION READY", capabilities:["Reputation signal","Behavior score","Request anomalies","Previous incidents","Recommended action"] },
  "bot-detection": { title:"Bot Detection", group:"Threat Detection", description:"Classify automated traffic using provider-neutral bot signals.", status:"INTEGRATION READY", capabilities:["Known bot","Unknown automation","Headless signal","Request velocity","Challenge recommendation"] },
  "malicious-requests": { title:"Malicious Requests", group:"Threat Detection", description:"Review requests classified as potentially hostile by connected detectors.", status:"INTEGRATION READY", capabilities:["Request classification","Target route","Severity","Risk score","Decision","Event timeline"] },
  "brute-force": { title:"Brute Force", group:"Threat Detection", description:"Detect repeated authentication failures and abnormal credential-attempt patterns.", status:"INTEGRATION READY", capabilities:["Attempt frequency","Account targeting","Source correlation","Rate-limit signal","Alert severity"] },
  "xss-attempts": { title:"XSS Attempts", group:"Threat Detection", description:"Display sanitized XSS-related detection events from a connected security provider.", status:"INTEGRATION READY", capabilities:["Detection category","Target route","Severity","Risk score","Mitigation status"] },
  "sql-injection-attempts": { title:"SQL Injection Attempts", group:"Threat Detection", description:"Display sanitized SQL-injection detection events from a connected security provider.", status:"INTEGRATION READY", capabilities:["Detection category","Target route","Severity","Risk score","Mitigation status"] },
  "ddos-indicators": { title:"DDoS Indicators", group:"Threat Detection", description:"Surface traffic-volume anomalies and rate-based DDoS indicators.", status:"INTEGRATION READY", capabilities:["Traffic spike","Requests per second","Source concentration","Route concentration","Rate-limit state","Provider mitigation status"] },

  "protection-firewall": { title:"Protection / Firewall", group:"Core Security Engine", description:"Central policy layer for provider-backed request decisions.", status:"INTEGRATION READY", capabilities:["IP Block / Allow","Country Block","Rate Limiting","Request Filtering","Bot Protection","Security Rules"] },
  "ip-block-allow": { title:"IP Block / Allow", group:"Protection / Firewall", description:"Manage explicit IP allow and deny policy for connected enforcement providers.", status:"INTEGRATION READY", capabilities:["Block IP","Allow IP","Reason","Expiry","Scope","Audit trail"] },
  "country-block": { title:"Country Block", group:"Protection / Firewall", description:"Apply country-level access policy when enforcement is connected.", status:"INTEGRATION READY", capabilities:["Country selector","Allow / block action","Website scope","Rule priority","Audit trail"] },
  "rate-limiting": { title:"Rate Limiting", group:"Protection / Firewall", description:"Configure request-rate thresholds for protected routes.", status:"INTEGRATION READY", capabilities:["Route scope","Request threshold","Time window","Action","Rule status","Logs"] },
  "request-filtering": { title:"Request Filtering", group:"Protection / Firewall", description:"Define high-level request filtering policy for supported provider integrations.", status:"INTEGRATION READY", capabilities:["Method","Path","Header conditions","Risk condition","Decision","Priority"] },
  "bot-protection": { title:"Bot Protection", group:"Protection / Firewall", description:"Configure bot handling policy for connected bot-management services.", status:"INTEGRATION READY", capabilities:["Allow verified bots","Challenge automation","Block high-risk bots","Rate limit unknown bots","Audit decisions"] },
  "security-rules": { title:"Security Rules", group:"Protection / Firewall", description:"Build provider-neutral security rules and decision logic.", status:"INTEGRATION READY", capabilities:["Conditions","AND / OR logic","Action","Priority","Enable / disable","Test result"] },

  "security-alerts": { title:"Security Alerts", group:"Core Security Engine", description:"Central alerting workspace for normalized security events.", status:"DEMO TELEMETRY", capabilities:["Critical Alert","High Risk","Medium Risk","Email Alert","Dashboard Notification"] },
  "critical-alerts": { title:"Critical Alert", group:"Security Alerts", description:"Highest-priority security notifications requiring immediate review.", status:"DEMO TELEMETRY", capabilities:["Critical severity","Affected website","Threat category","Risk score","Recommended review"] },
  "high-risk-alerts": { title:"High Risk", group:"Security Alerts", description:"High-severity security notifications and event context.", status:"DEMO TELEMETRY", capabilities:["High severity","Affected route","Source context","Risk score","Status"] },
  "medium-risk-alerts": { title:"Medium Risk", group:"Security Alerts", description:"Medium-severity security notifications and event context.", status:"DEMO TELEMETRY", capabilities:["Medium severity","Affected route","Source context","Risk score","Status"] },
  "email-alerts": { title:"Email Alert", group:"Security Alerts", description:"Email notification channel for selected security events.", status:"INTEGRATION READY", capabilities:["Recipient list","Severity threshold","Website scope","Digest mode","Delivery status"] },
  "dashboard-notifications": { title:"Dashboard Notification", group:"Security Alerts", description:"In-product notification center for security events and operational notices.", status:"DEMO TELEMETRY", capabilities:["Unread count","Severity","Timestamp","Website","Event link","Acknowledge state"] },

  "visitor-ip-address": { title:"IP Address", group:"Visitor Intelligence", description:"IP-centric visitor intelligence and session correlation.", status:"DEMO TELEMETRY", capabilities:["IP Address","Country","Sessions","Request count","Risk score","Threat history"] },
  "geographic-data": { title:"Geographic Data", group:"Visitor Intelligence", description:"Geographic distribution of visitor and threat activity.", status:"DEMO TELEMETRY", capabilities:["Country","City","Visitor count","Threat count","Traffic share"] },
  "device-information": { title:"Device Information", group:"Visitor Intelligence", description:"Device breakdown across visitor sessions.", status:"DEMO TELEMETRY", capabilities:["Device type","Session count","Browser","OS","Risk distribution"] },
  "browser-information": { title:"Browser Information", group:"Visitor Intelligence", description:"Browser-level visitor analytics and risk context.", status:"DEMO TELEMETRY", capabilities:["Browser family","Version","Sessions","Headless indicator","Risk distribution"] },
  "referral-source": { title:"Referral Source", group:"Visitor Intelligence", description:"Understand where website sessions originated.", status:"DEMO TELEMETRY", capabilities:["Direct","Organic search","Referral","Social","Campaign source"] },
  "pages-visited": { title:"Pages Visited", group:"Visitor Intelligence", description:"Route and page activity across tracked sessions.", status:"DEMO TELEMETRY", capabilities:["Page path","Views","Unique sessions","Average risk","Recent activity"] },
  "session-activity": { title:"Session Activity", group:"Visitor Intelligence", description:"Session-level timeline of page and request activity.", status:"DEMO TELEMETRY", capabilities:["Session start","Pages visited","Requests","Duration","Risk changes","Final status"] },

  "critical-threats": { title:"Critical Threats", group:"Threat Center", description:"Filter threat events to critical severity.", status:"DEMO TELEMETRY", capabilities:["Critical events","Source IP","Target route","Risk score","Action","Status"] },
  "blocked-threats": { title:"Blocked Threats", group:"Threat Center", description:"Threat events where the configured provider decision was block or rate-limit.", status:"DEMO TELEMETRY", capabilities:["Blocked events","Decision","Source","Target","Reason","Timeline"] },
  "suspicious-activity": { title:"Suspicious Activity", group:"Threat Center", description:"Review anomalous visitor and request behavior requiring investigation.", status:"DEMO TELEMETRY", capabilities:["Anomaly type","Source","Target","Risk score","Status","Related events"] },
  "threat-details": { title:"Threat Details", group:"Threat Center", description:"Detailed normalized event view for a selected security incident.", status:"DEMO TELEMETRY", capabilities:["Event ID","Threat type","Severity","Source IP","Target URL","Risk score","Decision","Timeline"] },
  "ip-reputation": { title:"IP Reputation", group:"Threat Center", description:"Provider-backed IP reputation lookup and event correlation.", status:"INTEGRATION READY", capabilities:["Reputation status","Provider signal","Risk score","Observed events","Recommended action"] },
  "threat-timeline": { title:"Threat Timeline", group:"Threat Center", description:"Chronological view of normalized security events.", status:"DEMO TELEMETRY", capabilities:["Event timestamp","Severity","Threat type","Source","Target","Decision"] },
  "take-action": { title:"Take Action", group:"Threat Center", description:"Central action workspace for approved security policy changes.", status:"INTEGRATION READY", capabilities:["Block IP","Allow IP","Create Rule","Add note","Audit action"] },
  "block-ip": { title:"Block IP", group:"Threat Center", description:"Create a provider-backed IP block action after review.", status:"INTEGRATION READY", capabilities:["IP address","Website scope","Reason","Expiry","Approval","Audit log"] },
  "allow-ip": { title:"Allow IP", group:"Threat Center", description:"Create an explicit IP allow policy after review.", status:"INTEGRATION READY", capabilities:["IP address","Website scope","Reason","Expiry","Approval","Audit log"] },
  "create-rule": { title:"Create Rule", group:"Threat Center", description:"Create a reusable security rule from an investigated event.", status:"INTEGRATION READY", capabilities:["Source event","Condition","Action","Scope","Priority","Status"] },

  "ip-rules": { title:"IP Rules", group:"Firewall", description:"Manage IP allow and deny rule configuration.", status:"INTEGRATION READY", capabilities:["IP / CIDR","Action","Website","Priority","Expiry","Status"] },
  "country-rules": { title:"Country Rules", group:"Firewall", description:"Manage country-level access policy.", status:"INTEGRATION READY", capabilities:["Country","Action","Website","Priority","Status"] },
  "firewall-rate-limiting": { title:"Rate Limiting", group:"Firewall", description:"Configure rate-limit rules for routes and request groups.", status:"INTEGRATION READY", capabilities:["Route","Threshold","Window","Action","Priority","Status"] },
  "bot-rules": { title:"Bot Rules", group:"Firewall", description:"Define bot-management decisions for supported integrations.", status:"INTEGRATION READY", capabilities:["Bot class","Condition","Action","Website","Status"] },
  "custom-rules": { title:"Custom Rules", group:"Firewall", description:"Compose provider-neutral custom security policy.", status:"INTEGRATION READY", capabilities:["Conditions","Logic","Action","Scope","Priority","Status"] },
  "firewall-logs": { title:"Firewall Logs", group:"Firewall", description:"Review request decisions and enforcement outcomes from connected providers.", status:"INTEGRATION READY", capabilities:["Timestamp","Rule","Request","Decision","Source IP","Provider result"] },

  "security-analytics": { title:"Security Analytics", group:"Analytics & Reports", description:"Security event trends, severity mix and posture indicators.", status:"DEMO TELEMETRY", capabilities:["Threat trend","Severity mix","Blocked events","Risk trend","Top categories"] },
  "threat-analytics": { title:"Threat Analytics", group:"Analytics & Reports", description:"Threat-centric trend and category analysis.", status:"DEMO TELEMETRY", capabilities:["Threat categories","Top sources","Top targets","Severity trend","Decision mix"] },
  "traffic-analytics": { title:"Traffic Analytics", group:"Analytics & Reports", description:"Website traffic patterns and request-volume analysis.", status:"DEMO TELEMETRY", capabilities:["Requests","Visitors","Traffic sources","Countries","Devices","Peak periods"] },
  "daily-reports": { title:"Daily Reports", group:"Analytics & Reports", description:"Daily security and traffic report workspace.", status:"DEMO TELEMETRY", capabilities:["Daily visitors","Daily threats","Blocked requests","Uptime","Top events"] },
  "weekly-reports": { title:"Weekly Reports", group:"Analytics & Reports", description:"Weekly security and traffic report workspace.", status:"DEMO TELEMETRY", capabilities:["7-day trend","Threat summary","Visitor summary","Rule activity","Alerts"] },
  "monthly-reports": { title:"Monthly Reports", group:"Analytics & Reports", description:"Monthly security and traffic report workspace.", status:"DEMO TELEMETRY", capabilities:["30-day trend","Threat summary","Visitor summary","Uptime","Security posture"] },
  "export-pdf": { title:"Export PDF", group:"Analytics & Reports", description:"PDF report generation pipeline for selected report types.", status:"INTEGRATION READY", capabilities:["Report type","Date range","Website","Branding","Generation status"] },
  "export-csv": { title:"Export CSV", group:"Analytics & Reports", description:"CSV export pipeline for tabular analytics and events.", status:"INTEGRATION READY", capabilities:["Dataset","Date range","Website","Columns","Export status"] },

  "add-website": { title:"Add Website", group:"Website Management", description:"Register a website in the WebShield workspace before verification.", status:"INTEGRATION READY", capabilities:["Domain","Display name","Environment","Owner organization","Initial status"] },
  "connect-domain": { title:"Connect Domain", group:"Website Management", description:"Connect a registered domain to the WebShield integration workflow.", status:"INTEGRATION READY", capabilities:["Domain","Verification token","DNS guidance","Collector status","Provider status"] },
  "website-verification": { title:"Verification", group:"Website Management", description:"Verify domain ownership before enabling production integrations.", status:"INTEGRATION READY", capabilities:["Verification token","DNS / file method","Verification state","Last checked","Retry"] },
  "security-status": { title:"Security Status", group:"Website Management", description:"Combined view of passive posture and connected protection services.", status:"LIVE PASSIVE", capabilities:["Passive security score","HTTPS","Security headers","Integration state","Protection provider state"] },
  "ssl-status": { title:"SSL Status", group:"Website Management", description:"HTTPS and transport posture from the live passive scanner.", status:"LIVE PASSIVE", capabilities:["HTTPS enabled","HTTP redirect","Final URL","HSTS presence","Transport status"] },
  "dns-integration": { title:"DNS / Integration", group:"Website Management", description:"Track DNS and security-provider integration readiness.", status:"INTEGRATION READY", capabilities:["DNS state","Verification state","Collector state","WAF provider","Last sync"] },
  "website-api-key": { title:"API Key", group:"Website Management", description:"Manage scoped website integration credentials without exposing full secrets after creation.", status:"INTEGRATION READY", capabilities:["Key name","Scope","Prefix","Created date","Last used","Revoke"] },
  "website-settings": { title:"Website Settings", group:"Website Management", description:"Per-website security, alerting and retention preferences.", status:"INTEGRATION READY", capabilities:["Website name","Environment","Alert thresholds","Retention","Default rules","Integrations"] }
};
