export const clientNav = [
  ["#security-dashboard", "SECURITY DASHBOARD"],
  ["dashboard", "Dashboard"],

  ["#core-security", "CORE SECURITY ENGINE"],
  ["real-time-monitoring", "Real-Time Monitoring"],
  ["visitor-tracking", "• Visitor Tracking"],
  ["ip-monitoring", "• IP Monitoring"],
  ["country-location", "• Country / Location"],
  ["device-monitoring", "• Device"],
  ["browser-monitoring", "• Browser"],
  ["os-monitoring", "• Operating System"],
  ["threat-detection", "Threat Detection"],
  ["suspicious-ip", "• Suspicious IP"],
  ["bot-detection", "• Bot Detection"],
  ["malicious-requests", "• Malicious Requests"],
  ["brute-force", "• Brute Force"],
  ["xss-attempts", "• XSS Attempts"],
  ["sql-injection-attempts", "• SQL Injection Attempts"],
  ["ddos-indicators", "• DDoS Indicators"],
  ["protection-firewall", "Protection / Firewall"],
  ["ip-block-allow", "• IP Block / Allow"],
  ["country-block", "• Country Block"],
  ["rate-limiting", "• Rate Limiting"],
  ["request-filtering", "• Request Filtering"],
  ["bot-protection", "• Bot Protection"],
  ["security-rules", "• Security Rules"],
  ["security-alerts", "Security Alerts"],
  ["critical-alerts", "• Critical Alert"],
  ["high-risk-alerts", "• High Risk"],
  ["medium-risk-alerts", "• Medium Risk"],
  ["email-alerts", "• Email Alert"],
  ["dashboard-notifications", "• Dashboard Notification"],

  ["#visitor-intelligence", "VISITOR INTELLIGENCE"],
  ["live-visitors", "Live Visitors"],
  ["visitor-history", "Visitor History"],
  ["visitor-ip-address", "IP Address"],
  ["geographic-data", "Geographic Data"],
  ["device-information", "Device Information"],
  ["browser-information", "Browser Information"],
  ["referral-source", "Referral Source"],
  ["pages-visited", "Pages Visited"],
  ["session-activity", "Session Activity"],

  ["#threat-center", "THREAT CENTER"],
  ["threat-center", "All Threats"],
  ["critical-threats", "Critical Threats"],
  ["blocked-threats", "Blocked Threats"],
  ["suspicious-activity", "Suspicious Activity"],
  ["threat-details", "Threat Details"],
  ["ip-reputation", "IP Reputation"],
  ["threat-timeline", "Threat Timeline"],
  ["take-action", "Take Action"],
  ["block-ip", "• Block IP"],
  ["allow-ip", "• Allow IP"],
  ["create-rule", "• Create Rule"],

  ["#firewall", "FIREWALL"],
  ["firewall", "Web Application Firewall"],
  ["ip-rules", "IP Rules"],
  ["country-rules", "Country Rules"],
  ["firewall-rate-limiting", "Rate Limiting"],
  ["bot-rules", "Bot Rules"],
  ["custom-rules", "Custom Rules"],
  ["firewall-logs", "Firewall Logs"],

  ["#analytics-reports", "ANALYTICS & REPORTS"],
  ["analytics", "Visitor Analytics"],
  ["security-analytics", "Security Analytics"],
  ["threat-analytics", "Threat Analytics"],
  ["traffic-analytics", "Traffic Analytics"],
  ["reports", "Reports"],
  ["daily-reports", "• Daily Reports"],
  ["weekly-reports", "• Weekly Reports"],
  ["monthly-reports", "• Monthly Reports"],
  ["export-pdf", "• Export PDF"],
  ["export-csv", "• Export CSV"],

  ["#website-management", "WEBSITE MANAGEMENT"],
  ["websites", "Websites / Security Scan"],
  ["add-website", "Add Website"],
  ["connect-domain", "Connect Domain"],
  ["website-verification", "Verification"],
  ["security-status", "Security Status"],
  ["ssl-status", "SSL Status"],
  ["dns-integration", "DNS / Integration"],
  ["website-api-key", "API Key"],
  ["website-settings", "Website Settings"],

  ["#workspace", "WORKSPACE"],
  ["alerts", "Alerts"],
  ["api-integrations", "API & Integrations"],
  ["billing", "Billing"],
  ["team", "Team"],
  ["settings", "Settings"],
  ["support", "Support"]
] as const;

export const adminNav = [
  ["dashboard", "Admin Dashboard"], ["clients", "Clients"], ["websites", "Websites"],
  ["security-events", "Security Events"], ["threat-events", "Threat Events"], ["users", "Users"],
  ["plans", "Plans"], ["subscriptions", "Subscriptions"], ["system-logs", "System Logs"],
  ["support-tickets", "Support Tickets"], ["system-settings", "System Settings"]
] as const;
