import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "@/components/icons";
import { Logo } from "@/components/logo";

const pages: Record<string,{title:string;kicker:string;intro:string;items:string[]}>= {
  product: { title:"WebShield Product Overview", kicker:"PRODUCT", intro:"A unified website security operations workspace for monitoring traffic, organizing security events and managing protection configuration.", items:["Multi-website security workspace","Visitor and request visibility","Threat investigation workflows","Firewall policy configuration","Analytics, reports and alerts","Provider-neutral security engine"] },
  features: { title:"Security visibility without fake claims", kicker:"FEATURES", intro:"WebShield V1 focuses on operational visibility and clean integration boundaries so production providers can be connected safely later.", items:["Live visitor monitoring architecture","Threat Center with severity and risk","IP, country, bot and rate-limit rule models","Website verification and integration status","Security and visitor analytics","API, webhook and team access foundations"] },
  "how-it-works": { title:"From request signal to decision", kicker:"ARCHITECTURE", intro:"Incoming requests move through modular collection, normalization, detection, scoring, rules and decision services before events reach the dashboard.", items:["Request Collector","Normalizer","Threat Detection Engine","Risk Scoring","Security Rules","Decision Engine + Event Logger"] },
  pricing: { title:"WebShield Plans", kicker:"PRICING", intro:"The billing foundation supports FREE, STARTER, BUSINESS and ENTERPRISE plans. Payment processing remains integration-ready until a real provider is configured.", items:["FREE — 1 website / 10K visitors","STARTER — 3 websites / 100K visitors","BUSINESS — 10 websites / API + team access","ENTERPRISE — custom limits and integration"] },
  security: { title:"Security architecture", kicker:"SECURITY", intro:"WebShield is designed around least privilege, server-side authorization, tenant isolation, secret management and explicit separation of demo telemetry from production security data.", items:["Supabase RLS-ready multi-tenant schema","Server-side RBAC checks","Secure cookie session model","Audit log data model","Secret hashing and masked key display","Security headers and validated API boundaries"] },
  documentation: { title:"WebShield Documentation", kicker:"DOCUMENTATION", intro:"V1 documentation covers setup, architecture, demo mode, Supabase integration, API boundaries and production readiness checks.", items:["Getting started","Authentication and RBAC","Database schema and RLS","Security engine provider interfaces","Vercel deployment","Production checklist"] },
  contact: { title:"Contact Savrdh Technologies", kicker:"CONTACT", intro:"WebShield is a Savrdh Technologies product. Use the official company website for company contact information and product enquiries.", items:["Company: Savrdh Technologies","Product: WebShield","Tagline: Monitor. Detect. Protect.","Founder: Shailendra Choudhary","Official website: savrdhtechnology.com"] }
};

export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}

export default async function PublicPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const page=pages[slug]; if(!page) notFound();
  return <main className="marketing publicInner"><header className="publicNav container"><Logo/><nav><Link href="/product">Product</Link><Link href="/features">Features</Link><Link href="/pricing">Pricing</Link><Link href="/security">Security</Link><Link href="/documentation">Docs</Link><Link href="/contact">Contact</Link></nav><div className="navActions"><Link className="linkBtn" href="/login">Login</Link><Link className="btn small" href="/register">Get Started</Link></div></header><section className="innerHero container"><span className="eyebrow"><span className="pulseDot"/>{page.kicker}</span><h1>{page.title}</h1><p>{page.intro}</p></section><section className="container innerGrid">{page.items.map((x,i)=><article className="featureCard" key={x}><div className="featureIcon"><Icon name={i%3===0?"shield":i%3===1?"chart":"globe"}/></div><span className="innerNum">0{i+1}</span><h3>{x}</h3><p>{slug==="contact"?"Official product/company information.":"Part of the WebShield V1 scalable SaaS foundation."}</p></article>)}</section><section className="cta innerCta"><div className="container"><div><span>WEBSHIELD</span><h2>Monitor. Detect. Protect.</h2></div><Link className="btn" href="/login">Open WebShield <Icon name="chevron"/></Link></div></section><footer className="footer container"><Logo/><p>WebShield © 2026 Savrdh Technologies.</p><a href="https://www.savrdhtechnology.com">Official website</a></footer></main>;
}
